<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
      <Version>1.0.3</Version>
      <IsPackable>true</IsPackable>
     
    <RootNamespace>CustomerService.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="MagicOnion.Client" Version="7.0.9" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.3.9" />
    <PackageReference Include="PaymentService.Contracts" Version="1.0.5" />
  </ItemGroup>

</Project>
